// Auto-generated themes from _tokens.scss
// This file is generated by scripts/generate-themes.js
// Do not edit manually - changes will be overwritten

import type { Theme } from "./stylesApi";

// Light Theme (generated from _tokens.scss)
export const defaultLightTheme: Theme = {
  "colors": {
    "surface-0": "#121212",
    "surface-1": "#1e1e1e",
    "surface-2": "#2a2a2a",
    "surface-3": "#3c3c3c",
    "surface-4": "#5f6368",
    "surface-5": "#80868b",
    "gray-5": "#adb5bd",
    "gray-6": "#868e96",
    "gray-7": "#495057",
    "gray-8": "#343a40",
    "gray-9": "#212529",
    "blue-0": "#081c42",
    "blue-1": "#0d2f70",
    "blue-2": "#1447a3",
    "blue-3": "#1d5cd7",
    "blue-4": "#276ef1",
    "blue-5": "#5a8cf6",
    "blue-6": "#8ab4f8",
    "blue-7": "#c7d8fc",
    "blue-8": "#e2ecfe",
    "blue-9": "#f5f9ff",
    "red-0": "#fff5f5",
    "red-1": "#ffe3e3",
    "red-2": "#ffc9c9",
    "red-3": "#ffa8a8",
    "red-4": "#ff8787",
    "red-5": "#ff6b6b",
    "red-6": "#fa5252",
    "red-7": "#f03e3e",
    "red-8": "#e03131",
    "red-9": "#c92a2a",
    "green-0": "#ebfbee",
    "green-1": "#d3f9d8",
    "green-2": "#b2f2bb",
    "green-3": "#8ce99a",
    "green-4": "#69db7c",
    "green-5": "#51cf66",
    "green-6": "#40c057",
    "green-7": "#37b24d",
    "green-8": "#2f9e44",
    "green-9": "#2b8a3e",
    "yellow-0": "#fff9db",
    "yellow-1": "#fff3bf",
    "yellow-2": "#ffec99",
    "yellow-3": "#ffe066",
    "yellow-4": "#ffd43b",
    "yellow-5": "#fcc419",
    "yellow-6": "#fab005",
    "yellow-7": "#f59f00",
    "yellow-8": "#f08c00",
    "yellow-9": "#e67700",
    "violet-0": "#f3f0ff",
    "violet-1": "#e5dbff",
    "violet-2": "#d0bfff",
    "violet-3": "#b197fc",
    "violet-4": "#9775fa",
    "violet-5": "#845ef7",
    "violet-6": "#7950f2",
    "violet-7": "#7048e8",
    "violet-8": "#6741d9",
    "violet-9": "#5f3dc4",
    "grape-0": "#f8f0fc",
    "grape-1": "#f3d9fa",
    "grape-2": "#eebefa",
    "grape-3": "#e599f7",
    "grape-4": "#da77f2",
    "grape-5": "#cc5de8",
    "grape-6": "#be4bdb",
    "grape-7": "#ae3ec9",
    "grape-8": "#9c36b5",
    "grape-9": "#862e9c",
    "cyan-0": "#e3fafc",
    "cyan-1": "#c5f6fa",
    "cyan-2": "#99e9f2",
    "cyan-3": "#66d9e8",
    "cyan-4": "#3bc9db",
    "cyan-5": "#22b8cf",
    "cyan-6": "#15aabf",
    "cyan-7": "#1098ad",
    "cyan-8": "#0c8599",
    "cyan-9": "#087285",
    "orange-0": "#fff4e6",
    "orange-1": "#ffe8cc",
    "orange-2": "#ffdba8",
    "orange-3": "#ffc078",
    "orange-4": "#ffa94d",
    "orange-5": "#ff922b",
    "orange-6": "#fd7e14",
    "orange-7": "#f76707",
    "orange-8": "#e8590c",
    "orange-9": "#d9480f",
    "indigo-0": "#edf2ff",
    "indigo-1": "#dbe4ff",
    "indigo-2": "#bac8ff",
    "indigo-3": "#91a7ff",
    "indigo-4": "#748ffc",
    "indigo-5": "#5c7cfa",
    "indigo-6": "#4c6ef5",
    "indigo-7": "#4263eb",
    "indigo-8": "#3b5bdb",
    "indigo-9": "#364fc7",
    "teal-0": "#e6fcf5",
    "teal-1": "#c3fae8",
    "teal-2": "#96f2d7",
    "teal-3": "#63e6be",
    "teal-4": "#38d9a9",
    "teal-5": "#20c997",
    "teal-6": "#12b886",
    "teal-7": "#0ca678",
    "teal-8": "#099268",
    "teal-9": "#087f5b",
    "white": "#ffffff",
    "black": "#000000",
    "success": "#81c995",
    "warning": "#fbbc04",
    "error": "#f28b82",
    "info": "#8ab4f8",
    "primary": "#5a8cf6",
    "secondary": "#868e96",
    "surface": "#ffffff",
    "text": "#212529",
    "border": "#e0e0e0",
    "background": "#ffffff",
    "gray-0": "#f8f9fa",
    "gray-1": "#f1f3f4",
    "gray-2": "#e8eaed",
    "gray-3": "#dadce0",
    "gray-4": "#bdc1c6"
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "48px"
  },
  "typography": {
    "h1": {
      "fontSize": "3rem",
      "lineHeight": "1",
      "fontWeight": "bold"
    },
    "h2": {
      "fontSize": "2.25rem",
      "lineHeight": "2.5rem",
      "fontWeight": "bold"
    },
    "h3": {
      "fontSize": "1.875rem",
      "lineHeight": "2.25rem",
      "fontWeight": "semibold"
    },
    "h4": {
      "fontSize": "1.5rem",
      "lineHeight": "2rem",
      "fontWeight": "semibold"
    },
    "h5": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "semibold"
    },
    "h6": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "semibold"
    },
    "text-xs": {
      "fontSize": "0.75rem",
      "lineHeight": "1rem",
      "fontWeight": "normal"
    },
    "text-sm": {
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": "normal"
    },
    "text-md": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "normal"
    },
    "text-lg": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    },
    "text-xl": {
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    }
  },
  "borderRadius": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "full": "9999px"
  },
  "shadows": {
    "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    "sm": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
    "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
  },
  "breakpoints": {
    "xs": "0px",
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  }
};

// Dark Theme (generated from light theme with inversions)
export const defaultDarkTheme: Theme = {
  "colors": {
    "surface-0": "#80868b",
    "surface-1": "#5f6368",
    "surface-2": "#3c3c3c",
    "surface-3": "#3c3c3c",
    "surface-4": "#5f6368",
    "surface-5": "#80868b",
    "gray-5": "#bdc1c6",
    "gray-6": "#dadce0",
    "gray-7": "#e8eaed",
    "gray-8": "#f1f3f4",
    "gray-9": "#f8f9fa",
    "blue-0": "#f5f9ff",
    "blue-1": "#e2ecfe",
    "blue-2": "#c7d8fc",
    "blue-3": "#8ab4f8",
    "blue-4": "#5a8cf6",
    "blue-5": "#5a8cf6",
    "blue-6": "#8ab4f8",
    "blue-7": "#c7d8fc",
    "blue-8": "#e2ecfe",
    "blue-9": "#f5f9ff",
    "red-0": "#c92a2a",
    "red-1": "#e03131",
    "red-2": "#f03e3e",
    "red-3": "#fa5252",
    "red-4": "#ff6b6b",
    "red-5": "#ff6b6b",
    "red-6": "#fa5252",
    "red-7": "#f03e3e",
    "red-8": "#e03131",
    "red-9": "#c92a2a",
    "green-0": "#2b8a3e",
    "green-1": "#2f9e44",
    "green-2": "#37b24d",
    "green-3": "#40c057",
    "green-4": "#51cf66",
    "green-5": "#51cf66",
    "green-6": "#40c057",
    "green-7": "#37b24d",
    "green-8": "#2f9e44",
    "green-9": "#2b8a3e",
    "yellow-0": "#e67700",
    "yellow-1": "#f08c00",
    "yellow-2": "#f59f00",
    "yellow-3": "#fab005",
    "yellow-4": "#fcc419",
    "yellow-5": "#fcc419",
    "yellow-6": "#fab005",
    "yellow-7": "#f59f00",
    "yellow-8": "#f08c00",
    "yellow-9": "#e67700",
    "violet-0": "#5f3dc4",
    "violet-1": "#6741d9",
    "violet-2": "#7048e8",
    "violet-3": "#7950f2",
    "violet-4": "#845ef7",
    "violet-5": "#845ef7",
    "violet-6": "#7950f2",
    "violet-7": "#7048e8",
    "violet-8": "#6741d9",
    "violet-9": "#5f3dc4",
    "grape-0": "#862e9c",
    "grape-1": "#9c36b5",
    "grape-2": "#ae3ec9",
    "grape-3": "#be4bdb",
    "grape-4": "#cc5de8",
    "grape-5": "#cc5de8",
    "grape-6": "#be4bdb",
    "grape-7": "#ae3ec9",
    "grape-8": "#9c36b5",
    "grape-9": "#862e9c",
    "cyan-0": "#087285",
    "cyan-1": "#0c8599",
    "cyan-2": "#1098ad",
    "cyan-3": "#15aabf",
    "cyan-4": "#22b8cf",
    "cyan-5": "#22b8cf",
    "cyan-6": "#15aabf",
    "cyan-7": "#1098ad",
    "cyan-8": "#0c8599",
    "cyan-9": "#087285",
    "orange-0": "#d9480f",
    "orange-1": "#e8590c",
    "orange-2": "#f76707",
    "orange-3": "#fd7e14",
    "orange-4": "#ff922b",
    "orange-5": "#ff922b",
    "orange-6": "#fd7e14",
    "orange-7": "#f76707",
    "orange-8": "#e8590c",
    "orange-9": "#d9480f",
    "indigo-0": "#364fc7",
    "indigo-1": "#3b5bdb",
    "indigo-2": "#4263eb",
    "indigo-3": "#4c6ef5",
    "indigo-4": "#5c7cfa",
    "indigo-5": "#5c7cfa",
    "indigo-6": "#4c6ef5",
    "indigo-7": "#4263eb",
    "indigo-8": "#3b5bdb",
    "indigo-9": "#364fc7",
    "teal-0": "#087f5b",
    "teal-1": "#099268",
    "teal-2": "#0ca678",
    "teal-3": "#12b886",
    "teal-4": "#20c997",
    "teal-5": "#20c997",
    "teal-6": "#12b886",
    "teal-7": "#0ca678",
    "teal-8": "#099268",
    "teal-9": "#087f5b",
    "white": "#ffffff",
    "black": "#000000",
    "success": "#81c995",
    "warning": "#fbbc04",
    "error": "#f28b82",
    "info": "#8ab4f8",
    "primary": "#5a8cf6",
    "secondary": "#868e96",
    "surface": "#0f172a",
    "text": "#f8fafc",
    "border": "#475569",
    "background": "#0f172a",
    "gray-0": "#f8f9fa",
    "gray-1": "#f1f3f4",
    "gray-2": "#e8eaed",
    "gray-3": "#dadce0",
    "gray-4": "#bdc1c6"
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "48px"
  },
  "typography": {
    "h1": {
      "fontSize": "3rem",
      "lineHeight": "1",
      "fontWeight": "bold"
    },
    "h2": {
      "fontSize": "2.25rem",
      "lineHeight": "2.5rem",
      "fontWeight": "bold"
    },
    "h3": {
      "fontSize": "1.875rem",
      "lineHeight": "2.25rem",
      "fontWeight": "semibold"
    },
    "h4": {
      "fontSize": "1.5rem",
      "lineHeight": "2rem",
      "fontWeight": "semibold"
    },
    "h5": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "semibold"
    },
    "h6": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "semibold"
    },
    "text-xs": {
      "fontSize": "0.75rem",
      "lineHeight": "1rem",
      "fontWeight": "normal"
    },
    "text-sm": {
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": "normal"
    },
    "text-md": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "normal"
    },
    "text-lg": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    },
    "text-xl": {
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    }
  },
  "borderRadius": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "full": "9999px"
  },
  "shadows": {
    "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    "sm": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
    "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
  },
  "breakpoints": {
    "xs": "0px",
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  }
};

// Default theme export
export const defaultTheme = defaultLightTheme;

// Theme types
export type ThemeMode = "light" | "dark";
export type ThemeName = "default-light" | "default-dark";

// Theme mapping
export const themes: Record<ThemeName, Theme> = {
  "default-light": defaultLightTheme,
  "default-dark": defaultDarkTheme,
};
