// Auto-generated themes from _tokens.scss
// This file is generated by scripts/generate-themes.js
// Do not edit manually - changes will be overwritten

import type { Theme } from "./stylesApi";

// Light Theme (generated from _tokens.scss)
export const defaultLightTheme: Theme = {
  "colors": {
    "surface-0": "#121212",
    "surface-1": "#1e1e1e",
    "surface-2": "#232323",
    "surface-3": "#2a2a2a",
    "surface-4": "#2f2f2f",
    "surface-5": "#353535",
    "gray-5": "#adb5bd",
    "gray-6": "#868e96",
    "gray-7": "#495057",
    "gray-8": "#343a40",
    "gray-9": "#212529",
    "blue-0": "#e7f5ff",
    "blue-1": "#d0ebff",
    "blue-2": "#a5d8ff",
    "blue-3": "#74c0fc",
    "blue-4": "#4dabf7",
    "blue-5": "#339af0",
    "blue-6": "#228be6",
    "blue-7": "#1c7ed6",
    "blue-8": "#1971c2",
    "blue-9": "#1864ab",
    "red-0": "#fff5f5",
    "red-1": "#ffe3e3",
    "red-2": "#ffc9c9",
    "red-3": "#ffa8a8",
    "red-4": "#ff8787",
    "red-5": "#ff6b6b",
    "red-6": "#fa5252",
    "red-7": "#f03e3e",
    "red-8": "#e03131",
    "red-9": "#c92a2a",
    "green-0": "#ebfbee",
    "green-1": "#d3f9d8",
    "green-2": "#b2f2bb",
    "green-3": "#8ce99a",
    "green-4": "#69db7c",
    "green-5": "#51cf66",
    "green-6": "#40c057",
    "green-7": "#37b24d",
    "green-8": "#2f9e44",
    "green-9": "#2b8a3e",
    "yellow-0": "#fff9db",
    "yellow-1": "#fff3bf",
    "yellow-2": "#ffec99",
    "yellow-3": "#ffe066",
    "yellow-4": "#ffd43b",
    "yellow-5": "#fcc419",
    "yellow-6": "#fab005",
    "yellow-7": "#f59f00",
    "yellow-8": "#f08c00",
    "yellow-9": "#e67700",
    "white": "#ffffff",
    "black": "#000000",
    "primary": "#339af0",
    "secondary": "#868e96",
    "success": "#40c057",
    "warning": "#fab005",
    "error": "#fa5252",
    "info": "#339af0",
    "surface": "#ffffff",
    "text": "#212529",
    "border": "#e0e0e0",
    "background": "#ffffff",
    "gray-0": "#f8f9fa",
    "gray-1": "#f1f3f4",
    "gray-2": "#e8eaed",
    "gray-3": "#dadce0",
    "gray-4": "#bdc1c6"
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "48px"
  },
  "typography": {
    "h1": {
      "fontSize": "3rem",
      "lineHeight": "1",
      "fontWeight": "bold"
    },
    "h2": {
      "fontSize": "2.25rem",
      "lineHeight": "2.5rem",
      "fontWeight": "bold"
    },
    "h3": {
      "fontSize": "1.875rem",
      "lineHeight": "2.25rem",
      "fontWeight": "semibold"
    },
    "h4": {
      "fontSize": "1.5rem",
      "lineHeight": "2rem",
      "fontWeight": "semibold"
    },
    "h5": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "semibold"
    },
    "h6": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "semibold"
    },
    "text-xs": {
      "fontSize": "0.75rem",
      "lineHeight": "1rem",
      "fontWeight": "normal"
    },
    "text-sm": {
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": "normal"
    },
    "text-md": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "normal"
    },
    "text-lg": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    },
    "text-xl": {
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    }
  },
  "borderRadius": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "full": "9999px"
  },
  "shadows": {
    "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    "sm": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
    "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
  },
  "breakpoints": {
    "xs": "0px",
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  }
};

// Dark Theme (generated from light theme with inversions)
export const defaultDarkTheme: Theme = {
  "colors": {
    "surface-0": "#353535",
    "surface-1": "#2f2f2f",
    "surface-2": "#2a2a2a",
    "surface-3": "#2a2a2a",
    "surface-4": "#2f2f2f",
    "surface-5": "#353535",
    "gray-5": "#bdc1c6",
    "gray-6": "#dadce0",
    "gray-7": "#e8eaed",
    "gray-8": "#f1f3f4",
    "gray-9": "#f8f9fa",
    "blue-0": "#1864ab",
    "blue-1": "#1971c2",
    "blue-2": "#1c7ed6",
    "blue-3": "#228be6",
    "blue-4": "#339af0",
    "blue-5": "#339af0",
    "blue-6": "#228be6",
    "blue-7": "#1c7ed6",
    "blue-8": "#1971c2",
    "blue-9": "#1864ab",
    "red-0": "#c92a2a",
    "red-1": "#e03131",
    "red-2": "#f03e3e",
    "red-3": "#fa5252",
    "red-4": "#ff6b6b",
    "red-5": "#ff6b6b",
    "red-6": "#fa5252",
    "red-7": "#f03e3e",
    "red-8": "#e03131",
    "red-9": "#c92a2a",
    "green-0": "#2b8a3e",
    "green-1": "#2f9e44",
    "green-2": "#37b24d",
    "green-3": "#40c057",
    "green-4": "#51cf66",
    "green-5": "#51cf66",
    "green-6": "#40c057",
    "green-7": "#37b24d",
    "green-8": "#2f9e44",
    "green-9": "#2b8a3e",
    "yellow-0": "#e67700",
    "yellow-1": "#f08c00",
    "yellow-2": "#f59f00",
    "yellow-3": "#fab005",
    "yellow-4": "#fcc419",
    "yellow-5": "#fcc419",
    "yellow-6": "#fab005",
    "yellow-7": "#f59f00",
    "yellow-8": "#f08c00",
    "yellow-9": "#e67700",
    "white": "#ffffff",
    "black": "#000000",
    "primary": "#339af0",
    "secondary": "#868e96",
    "success": "#40c057",
    "warning": "#fab005",
    "error": "#fa5252",
    "info": "#339af0",
    "surface": "#0f172a",
    "text": "#f8fafc",
    "border": "#475569",
    "background": "#0f172a",
    "gray-0": "#f8f9fa",
    "gray-1": "#f1f3f4",
    "gray-2": "#e8eaed",
    "gray-3": "#dadce0",
    "gray-4": "#bdc1c6"
  },
  "spacing": {
    "xs": "4px",
    "sm": "8px",
    "md": "16px",
    "lg": "24px",
    "xl": "32px",
    "xxl": "48px"
  },
  "typography": {
    "h1": {
      "fontSize": "3rem",
      "lineHeight": "1",
      "fontWeight": "bold"
    },
    "h2": {
      "fontSize": "2.25rem",
      "lineHeight": "2.5rem",
      "fontWeight": "bold"
    },
    "h3": {
      "fontSize": "1.875rem",
      "lineHeight": "2.25rem",
      "fontWeight": "semibold"
    },
    "h4": {
      "fontSize": "1.5rem",
      "lineHeight": "2rem",
      "fontWeight": "semibold"
    },
    "h5": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "semibold"
    },
    "h6": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "semibold"
    },
    "text-xs": {
      "fontSize": "0.75rem",
      "lineHeight": "1rem",
      "fontWeight": "normal"
    },
    "text-sm": {
      "fontSize": "0.875rem",
      "lineHeight": "1.25rem",
      "fontWeight": "normal"
    },
    "text-md": {
      "fontSize": "1rem",
      "lineHeight": "1.5rem",
      "fontWeight": "normal"
    },
    "text-lg": {
      "fontSize": "1.125rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    },
    "text-xl": {
      "fontSize": "1.25rem",
      "lineHeight": "1.75rem",
      "fontWeight": "normal"
    }
  },
  "borderRadius": {
    "xs": "2px",
    "sm": "4px",
    "md": "6px",
    "lg": "8px",
    "xl": "12px",
    "full": "9999px"
  },
  "shadows": {
    "xs": "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    "sm": "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
    "md": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
    "lg": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
    "xl": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)"
  },
  "breakpoints": {
    "xs": "0px",
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  }
};

// Default theme export
export const defaultTheme = defaultLightTheme;

// Theme types
export type ThemeMode = "light" | "dark";
export type ThemeName = "default-light" | "default-dark";

// Theme mapping
export const themes: Record<ThemeName, Theme> = {
  "default-light": defaultLightTheme,
  "default-dark": defaultDarkTheme,
};
